In [1]:
import pandas as pd
import pandas_profiling
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()
print("length of dataset:", len(df))

length of dataset: 10000


In [4]:
x_weight = df["Weight"]
y_height = df["Height"]
x_weight_max = x_weight.max()
y_height_max = y_height.max()
print("x_weight_max:", x_weight_max)
print("y_height_max:", y_height_max)
x_weight_min = x_weight.min()
y_height_min = y_height.min()
print("x_weight_min:", x_weight_min)
print("y_height_min:", y_height_min)


m = len(y_height)

X = np.zeros((m, 2))

X[: ,0] = 1
X[: ,1] = x_weight
X

x_weight_max: 269.989698505106
y_height_max: 78.9987423463896
x_weight_min: 64.700126712753
y_height_min: 54.2631333250971


array([[  1.        , 241.89356318],
       [  1.        , 162.31047252],
       [  1.        , 212.74085556],
       ...,
       [  1.        , 128.47531878],
       [  1.        , 163.85246135],
       [  1.        , 113.64910268]])

In [5]:
y_height = np.array(y_height)
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_height)
y_height

array([73.84701702, 68.78190405, 74.11010539, ..., 63.86799221,
       69.03424313, 61.94424588])

In [6]:
theta

array([48.47790261,  0.11081279])

In [11]:
x_weight_100 = np.linspace(0, 270, len(x_weight)/1000)

plt.scatter(x_weight_100, y_height)
a = np.linspace(0, 270, 10000)
b = theta[0] + a * theta[1]
plt.plot(a, b)

TypeError: 'float' object cannot be interpreted as an integer